apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketmq-nameserver.fullname" . }}-configmap
  labels:
    {{- include "rocketmq-nameserver.labels" . | nindent 4 }}
data:
  namesrv.p: |
    listenPort={{ include "rocketmq-nameserver.port" . }}
    {{ .Values.configmap | indent 4 | trim }}
