# Default values for rocketmq-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
partition: 0

broker:
  clusterNameOverride: ""
  brokerNamePrefixOverride: ""
  tlsMode: disabled
  heapSize: "3G"
  enableStartupProbe: false
  startupProbeNamesrvAddr: ""
  nameServerHeadlessAddr: ""
  clusterName: "rocketmq-cluster-a"

config: ""

image:
  pullPolicy: IfNotPresent
  repository: "cn-cicd-repo-registry.cn-hangzhou.cr.aliyuncs.com/cicd/rocketmq"
  tag: "develop-44e58738-b644-430f-bd94-147cc8f3d731-centos-7"

nameOverride: ""
fullnameOverride: ""
namesrvAddr: ""

service:
  port: 10911

jvmMemory: " -Xms4g -Xmx4g -Xmn2g -XX:MaxDirectMemorySize=8g "
resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

nodeSelector: { }

tolerations: [ ]
